<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Debasish" failures="1" tests="1" name="Open Account Test" time="0.128" errors="0" timestamp="2024-01-04T16:06:25 IST">
  <testcase classname="in.debasish.testCases.OpenAccountTest" name="openAccountTest" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1">
      <![CDATA[java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
at in.debasish.utilities.TestUtil.getData(TestUtil.java:48)
... 25 more
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- openAccountTest -->
</testsuite> <!-- Open Account Test -->
